version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: subarna
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_DB: localtest_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U subarna -d localtest_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://subarna:passw0rd@postgres:5432/localtest_db
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: